### ISSUE TITLE
Error when loading table from example 'table performance' app

### ISSUE THREAD

**Issue by eebs11** [fico-xpress/vdlx-datagrid#24]
When loading any of the example data sets in the 'table performance' app, an error is thrown:  "Refused to apply style from .../vdlx-datagrid.css because its MIME type ('') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

(This is using Google Chrome Version 76.0.3809)

![DataGridError](https://user-images.githubusercontent.com/47503596/69078949-9129cb80-09fe-11ea-8d72-f7cfb371d7ba.png)

**Comment by ddetkovs** [comment]
This issue should be resolved with the last commit
