### ISSUE TITLE
Error when loading data grid from custom application

### ISSUE THREAD

**Issue by eebs11** [fico-xpress/vdlx-datagrid#25]
An error is thrown when attempting to load a data grid in a custom application.  The header of the error message is:  'Uncaught ReferenceError: $NGmv$var$arrayBufferTag is not defined...'

(This is using Google Chrome Version 76.0.3809)

The full error message is pasted below.

The VDL code is:
<vdl version="4.1">
 
    <vdl-include src="vdlx-datagrid/vdlx-datagrid.vdl"></vdl-include>
    <vdl-page>
        <vdl-section heading="Flight Legs">
 
            <vdlx-datagrid >
                <vdlx-datagrid-column set="fltLegIdxSet"></vdlx-datagrid-column>
                <vdlx-datagrid-column entity="fltLegKey"></vdlx-datagrid-column>
        </vdl-section>
    </vdl-page>
</vdl>

![DataGridError2](https://user-images.githubusercontent.com/47503596/69079796-5de83c00-0a00-11ea-810c-b6b951f096a7.png)

**Comment by ddetkovs** [comment]
Hi,
I've just pushed some changes, that will hopefully fix your issue. The process is the same: 

1. copy everything from `dist/insight/client_resources/vdlx-datagrid/` into `vdlx-datagrid` folder in your app
2. include vdlx-datagrid.vdl in your view with 
`<vdl-include src="vdlx-datagrid/vdlx-datagrid.vdl"></vdl-include>`

**Comment by eebs11** [comment]
Thanks Deniss!  I'll give it a try.

**Comment by eebs11** [comment]
Thanks Deniss!  That fixed everything up for me.  Works great!
