### ISSUE TITLE
How to pivot an index using vdl-index-filter

### ISSUE THREAD

**Issue by amarvin** [fico-xpress/vdlx-datagrid#33]
Excellent alternative table package! I'd like to use `vdlx-datagrid` with one of the indexes pivotted across columns, but it doesn't seem to work the same way as `vdl-table`:

```html
<!-- syntax with vdl-table pivots my_table with my_index1 across columns -->
<vdl-table>
  <vdl-table-column
      entity="my_table"
      heading="=c.label"
      vdl-repeat="=c in scenario.entities.my_index1">
    <vdl-index-filter set="my_index1" value="=c.value"/>
  </vdl-table-column>
</vdl-table>

<!-- syntax with vdlx-datagrid duplicates my_table len(my_index1) times -->
<vdlx-datagrid>
  <vdlx-datagrid-column
      entity="my_table"
      heading="=c.label"
      vdl-repeat="=c in scenario.entities.my_index1">
    <vdl-index-filter set="my_index1" value="=c.value"/>
  </vdlx-datagrid-column>
</vdlx-datagrid>
```

Can you add to the readme how to do this kind of pivoting, if its possible with the current `vdlx-datagrid`?

**Comment by timhemming-fico** [comment]
Sorry for the delayed response, we don't have anyone maintaining this issues board. It's best to contact FICO support or the community board as you mentioned. We're going to close the GitHub issues board for this project as we track support and issues elsewhere.

It should be possible to pivot index sets in the same way as `vdl-table`. There is an example of this in the latest `vdlx-datagrid` example app, see "PIVOT INDEX VALUES AS COLUMNS" in the "Index filtering" view. If you can't yet use VDL 4.7 but you're on VDL 4.6 you can download the latest 4.6.x release and example app https://github.com/fico-xpress/vdlx-datagrid/releases/tag/v4.6.3

**Comment by amarvin** [comment]
Thanks for the feedback, and also appreciate that this feature was added in the latest release.
