### ISSUE TITLE
Is server-side processing possible?

### ISSUE THREAD

**Issue by amarvin** [fico-xpress/vdlx-datagrid#34]
Some of my tables have 100k+ rows, which leads to long page load times. It seems that the render improvements from `vdlx-datagrid` won't help as most time is on receiving the data. I always use pagination, so is [server-side processing](https://datatables.net/reference/option/serverSide) an option either with `vdl-table` or `vdlx-datagrid`?

I tried with `vdl-table` using:
```html
<script>
  function vdl_table_faster(tableOptions) {
    tableOptions.overrides.serverSide = true;
    return tableOptions;
  }
</script>

<vdl-page>
  <vdl-table modifier="=vdl_table_faster" page-mode="paged">
    <vdl-table-column entity="my_big_entity"/>
  </vdl-table>
</vdl-page
```

but then the page returns a VDL error saying Invalid JSON Response. Is there a way to configure the FICO Insight JavaScript API to deliver server-side processing like this?

**Comment by amarvin** [comment]
Sorry if this Issue is more appropriate for FICO Support or the Community board, as it applies to core `vdl-table` as well.

**Comment by timhemming-fico** [comment]
Hi,

Sorry for the delayed response, we don't have anyone maintaining this issues board. It's best to contact FICO support or the community board as you mentioned. We're going to close the GitHub issues board for this project as we track support and issues elsewhere.

As of `vdlx-datagrid` release 4.7.0, it is possible to filter out specific index sets on the server-side by using `vdlx-datagrid-index-filter` at the `vdlx-datagrid` level. This reduces the data sent back from the server and processed by datagrid. But you have to structure your data to be indexed by a number of categories to benefit from this. You need to be using VDL 4.7 to make use of this release, see https://github.com/fico-xpress/vdlx-datagrid/releases. There is an example of the server-side index filtering in the example app that goes with the 4.7.x releases.

It's not possible to do any server-side processing with `vdl-table`.
